# 第一阶段：构建前端应用
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV VITE_BASE_URL=/backend/api/v1/chat
ENV VITE_HOST_URL=/backend
RUN corepack enable

WORKDIR /app
COPY ./frontend/ .
RUN rm -rf node_modules
FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

RUN pnpm run build

# 第二阶段：使用 Nginx 服务器
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf.template

COPY ./docker/start-nginx.sh /start-nginx.sh
RUN chmod +x /start-nginx.sh

# 暴露 Nginx 的端口
EXPOSE 80

# 启动脚本
CMD ["/start-nginx.sh"]
